In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

C:\Users\AlokVerma\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
df = pd.read_csv(r"C:\Users\AlokVerma\Desktop\BBD CSE AI ML\spam.csv")

In [4]:
df.head(5)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df.Category.value_counts()/len(df)*100

Category
ham     86.593683
spam    13.406317
Name: count, dtype: float64

In [7]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [8]:
df.head(5)

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
new_df = pd.read_csv('spam.csv')

In [10]:
new_df['Category'].replace({'ham':0,'spam':1}, inplace=True)

C:\Users\AlokVerma\AppData\Local\Temp\ipykernel_18724\2701969205.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  new_df['Category'].replace({'ham':0,'spam':1}, inplace=True)

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Category, Length: 5572, dtype: object

In [11]:
new_df.head(5)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [12]:
df.head(5)

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [13]:
df.shape

(5572, 3)

#### **Train Test Split**

In [14]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam,test_size=0.2)

In [15]:
X_train.shape

(4457,)

In [16]:
X_test.shape

(1115,)

In [17]:
X_train[:4]

2066    Cos daddy arranging time c wat time fetch ü ma...
5141    FREE for 1st week! No1 Nokia tone 4 ur mobile ...
3442    Get a FREE mobile video player FREE movie. To ...
534                                       I'll be late...
Name: Message, dtype: str

In [18]:
y_train[:4]

2066    0
5141    1
3442    1
534     0
Name: spam, dtype: int64

#### **Create bag of words representation using CountVectorizer**

In [19]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_test_cv = v.transform(X_test)

In [20]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59475 stored elements and shape (4457, 7789)>

In [21]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
X_train_cv.shape

(4457, 7789)

In [23]:
v.get_feature_names_out()[1771]

'cheaper'

In [24]:
v.vocabulary_

{'cos': 2036,
 'daddy': 2164,
 'arranging': 1083,
 'time': 6948,
 'wat': 7445,
 'fetch': 2843,
 'mah': 4345,
 'free': 3014,
 'for': 2965,
 '1st': 342,
 'week': 7489,
 'no1': 4824,
 'nokia': 4832,
 'tone': 7008,
 'ur': 7249,
 'mobile': 4583,
 'every': 2687,
 'just': 3903,
 'txt': 7146,
 'to': 6979,
 '8077': 652,
 'get': 3149,
 'txting': 7151,
 'and': 970,
 'tell': 6802,
 'mates': 4415,
 'www': 7687,
 'getzed': 3158,
 'co': 1886,
 'uk': 7171,
 'pobox': 5301,
 '36504': 461,
 'w45wq': 7390,
 '16': 322,
 'norm150p': 4851,
 'video': 7336,
 'player': 5278,
 'movie': 4649,
 'collect': 1909,
 'text': 6836,
 'go': 3191,
 '89105': 712,
 'its': 3794,
 'extra': 2755,
 'films': 2870,
 'can': 1657,
 'be': 1292,
 'ordered': 5018,
 'apply': 1032,
 '18': 326,
 'yrs': 7768,
 'only': 4985,
 'll': 4187,
 'late': 4051,
 'came': 1653,
 'look': 4223,
 'at': 1129,
 'the': 6863,
 'flat': 2913,
 'seems': 6035,
 'ok': 4954,
 'in': 3666,
 'his': 3472,
 '50s': 554,
 'is': 3774,
 'away': 1185,
 'alot': 931,
 'wiv': 7603,
 'work': 7638,
 'got': 3232,
 'woman': 7619,
 'coming': 1929,
 '30': 434,
 'too': 7020,
 'hope': 3514,
 'you': 7752,
 'are': 1056,
 'having': 3398,
 'good': 3215,
 'checking': 1779,
 'she': 6118,
 'find': 2878,
 'sent': 6064,
 'an': 965,
 'offline': 4942,
 'message': 4491,
 'know': 3990,
 'how': 3546,
 'anjola': 978,
 'now': 4875,
 'sorry': 6368,
 'not': 4860,
 'unsubscribe': 7228,
 'yet': 7738,
 'mob': 4581,
 'offer': 4934,
 'package': 5086,
 'has': 3379,
 'min': 4519,
 'term': 6820,
 'of': 4927,
 '54': 562,
 'weeks': 7494,
 'pls': 5292,
 'resubmit': 5790,
 'request': 5758,
 'after': 861,
 'expiry': 2743,
 'reply': 5753,
 'themob': 6873,
 'help': 3434,
 'more': 4626,
 'info': 3699,
 've': 7311,
 'it': 3786,
 'he': 3403,
 'send': 6056,
 'me': 4439,
 'entry': 2636,
 'weekly': 7493,
 'comp': 1938,
 'chance': 1743,
 'win': 7570,
 'ipod': 3763,
 'pod': 5316,
 '80182': 648,
 'std': 6506,
 'rate': 5612,
 '08452810073': 67,
 'details': 2294,
 'check': 1775,
 'out': 5047,
 'our': 5044,
 'newest': 4793,
 'selection': 6043,
 'content': 1999,
 'games': 3100,
 'tones': 7009,
 'gossip': 3231,
 'babes': 1203,
 'sport': 6448,
 'keep': 3937,
 'your': 7757,
 'fit': 2899,
 'funky': 3077,
 'wap': 7431,
 '82468': 662,
 'pass': 5136,
 'dis': 2358,
 'all': 919,
 'contacts': 1997,
 'see': 6029,
 'red': 5686,
 'luv': 4294,
 'wid': 7557,
 'blue': 1427,
 'put': 5549,
 'smile': 6293,
 'on': 4973,
 'my': 4708,
 'face': 2764,
 'purple': 5542,
 'realy': 5651,
 'hot': 3533,
 'pink': 5252,
 'so': 6322,
 'swt': 6708,
 'orange': 5013,
 'thnk': 6903,
 'lyk': 4304,
 'green': 3272,
 'wana': 7424,
 'yelow': 7730,
 'wnt': 7615,
 'bck': 1281,
 'black': 1395,
 'jealous': 3834,
 'brown': 1554,
 'miss': 4546,
 'nw': 4901,
 'plz': 5296,
 'giv': 3174,
 'one': 4979,
 'color': 1915,
 'thanks': 6852,
 'ringtone': 5828,
 'order': 5017,
 'ref': 5690,
 'number': 4891,
 'r836': 5579,
 'will': 7568,
 'charged': 1754,
 '50': 542,
 'should': 6164,
 'arrive': 1086,
 'please': 5284,
 'call': 1633,
 'customer': 2146,
 'services': 6078,
 '09065069154': 219,
 'house': 3541,
 'maid': 4349,
 'murderer': 4696,
 'coz': 2065,
 'man': 4366,
 'was': 7438,
 'murdered': 4695,
 'lt': 4277,
 'gt': 3293,
 'th': 6847,
 'january': 3821,
 'as': 1095,
 'public': 5526,
 'holiday': 3495,
 'govt': 3240,
 'instituitions': 3727,
 'closed': 1868,
 'including': 3674,
 'post': 5363,
 'office': 4938,
 'understand': 7196,
 'amazing': 945,
 'if': 3626,
 'rearrange': 5653,
 'these': 6882,
 'letters': 4115,
 'gives': 3177,
 'same': 5937,
 'meaning': 4443,
 'dormitory': 2443,
 'dirty': 2357,
 'room': 5858,
 'astronomer': 1126,
 'moon': 4624,
 'starer': 6487,
 'eyes': 2761,
 'they': 6886,
 'election': 2578,
 'results': 5792,
 'lies': 4127,
 'lets': 4113,
 'recount': 5682,
 'mother': 4637,
 'law': 4065,
 'hitler': 3475,
 'eleven': 2582,
 'plus': 5294,
 'two': 7144,
 'twelve': 7137,
 'might': 4510,
 'come': 1923,
 'kerala': 3945,
 'days': 2201,
 'prepared': 5417,
 'take': 6734,
 'leave': 4088,
 'once': 4977,
 'finalise': 2874,
 'dont': 2433,
 'plan': 5268,
 'any': 1001,
 'travel': 7076,
 'during': 2516,
 'visit': 7357,
 'need': 4763,
 'finish': 2883,
 'urgent': 7253,
 'works': 7644,
 'done': 2431,
 'next': 4800,
 'space': 6388,
 'everything': 2695,
 'want': 7426,
 'remember': 5723,
 'furniture': 3080,
 'yours': 7761,
 'around': 1079,
 'when': 7532,
 'move': 4646,
 'lock': 4202,
 'locks': 4203,
 'key': 3949,
 'with': 7596,
 'jenne': 3839,
 'edison': 2550,
 'rightly': 5821,
 'said': 5923,
 'fool': 2957,
 'ask': 1104,
 'questions': 5566,
 'than': 6848,
 'wise': 7588,
 'answer': 990,
 'why': 7552,
 'us': 7263,
 'speechless': 6408,
 'viva': 7362,
 'gm': 3185,
 'gn': 3187,
 'ge': 3129,
 'gnt': 3189,
 'don': 2429,
 'run': 5897,
 'frm': 3041,
 'walk': 7411,
 'slowly': 6281,
 'amp': 959,
 'kills': 3969,
 'that': 6859,
 'care': 1679,
 'enough': 2624,
 'stop': 6536,
 'probably': 5464,
 'still': 6526,
 'going': 3204,
 'over': 5065,
 'some': 6335,
 'stuff': 6585,
 'here': 3446,
 'yes': 7735,
 'princess': 5448,
 'make': 4357,
 'moan': 4580,
 'there': 6880,
 'friday': 3031,
 'pongal': 5334,
 'do': 2394,
 'news': 4796,
 'from': 3051,
 'place': 5263,
 'went': 7511,
 'fast': 2804,
 'asleep': 1111,
 'dear': 2212,
 'by': 1617,
 'point': 5319,
 'we': 7466,
 'iron': 3767,
 'this': 6900,
 'weekend': 7491,
 'hungry': 3579,
 'buy': 1607,
 'food': 2956,
 'lei': 4101,
 'but': 1602,
 'mum': 4687,
 'yun': 7773,
 'dun': 2511,
 'wan': 7423,
 'juz': 3908,
 'little': 4179,
 'bit': 1389,
 'yo': 7747,
 'watching': 7450,
 'netflix': 4782,
 'dave': 2198,
 'final': 2873,
 'notice': 4866,
 'tenerife': 6816,
 'or': 5010,
 '5000': 544,
 'cash': 1701,
 'award': 1183,
 '09061743806': 202,
 'landline': 4030,
 'tcs': 6777,
 'sae': 5917,
 'box326': 1483,
 'cw25wx': 2156,
 '150ppm': 315,
 'started': 6492,
 'requests': 5759,
 'pain': 5094,
 'back': 1211,
 'bed': 1308,
 'double': 2448,
 'coins': 1901,
 'factory': 2768,
 'gotta': 3237,
 'nitros': 4820,
 'somebody': 6337,
 'set': 6081,
 'up': 7232,
 'website': 7480,
 'where': 7536,
 'play': 5276,
 'hold': 3491,
 'em': 2587,
 'using': 7275,
 'eve': 2679,
 'online': 4983,
 'spacebucks': 6389,
 'slave': 6261,
 'doing': 2419,
 'again': 867,
 'into': 3743,
 'shell': 6123,
 'unconsciously': 7191,
 'avoiding': 1178,
 'making': 4361,
 'unhappy': 7205,
 'well': 7506,
 'no': 4823,
 'worries': 7649,
 'maga': 4339,
 'money': 4610,
 'yesterday': 7737,
 'oh': 4949,
 'wanna': 7425,
 'laid': 4025,
 '2nite': 418,
 'real': 5640,
 'dogging': 2413,
 'locations': 4200,
 'direct': 2351,
 'join': 3867,
 'largest': 4046,
 'network': 4784,
 'park': 5124,
 '69696': 597,
 'nyt': 4906,
 'ec2a': 2543,
 '3lp': 473,
 'msg': 4660,
 'didnt': 2321,
 'anything': 1009,
 'da': 2160,
 'hi': 3457,
 'hun': 3575,
 'im': 3643,
 'comin': 1928,
 'every1': 2688,
 'ava': 1166,
 'goodtime': 3226,
 'oli': 4966,
 'rang': 5608,
 'melnite': 4469,
 'ifink': 3628,
 'mite': 4559,
 'sorted': 6371,
 'il': 3638,
 'explain': 2744,
 'everythin': 2694,
 'mon': 4607,
 'l8rs': 4012,
 'today': 6985,
 'day': 2200,
 'ever': 2686,
 'angry': 975,
 'misbehaved': 4543,
 'hurt': 3586,
 'slap': 6260,
 'urself': 7262,
 'bcoz': 1286,
 'fault': 2813,
 'basically': 1260,
 'many': 4380,
 'things': 6891,
 'antibiotic': 1000,
 'used': 7268,
 'chest': 1791,
 'abdomen': 754,
 'gynae': 3318,
 'infections': 3696,
 'even': 2681,
 'bone': 1443,
 'outside': 5058,
 'already': 932,
 'person': 5200,
 'who': 7546,
 'sms': 6303,
 'survey': 6677,
 'better': 1354,
 'bb': 1275,
 'wont': 7628,
 'use': 7267,
 'wife': 7560,
 'them': 6870,
 'doctor': 2401,
 'haha': 3327,
 'leh': 4100,
 'later': 4054,
 'tuition': 7125,
 'looking': 4227,
 'empty': 2600,
 'slots': 6276,
 'driving': 2482,
 'lessons': 4111,
 'watch': 7446,
 'infernal': 3697,
 'affair': 850,
 'trust': 7106,
 'new': 4791,
 'asap': 1097,
 'try': 7109,
 'then': 6874,
 'hostel': 3531,
 'thanx': 6857,
 'spent': 6418,
 '2geva': 399,
 'bin': 1379,
 'mint': 4535,
 'baby': 1205,
 'xxxx': 7703,
 'squeeeeeze': 6464,
 'christmas': 1828,
 'hug': 3565,
 'lik': 4138,
 'frndshp': 3046,
 'den': 2263,
 'cute': 2150,
 'luvd': 4295,
 'lucky': 4284,
 'none': 4839,
 'people': 5184,
 'hate': 3385,
 'am': 944,
 'searching': 6014,
 'dual': 2500,
 'sim': 6210,
 'pa': 5083,
 'deus': 2298,
 'ex': 2710,
 'game': 3099,
 'early': 2529,
 'yr': 7767,
 'okay': 4955,
 'clarification': 1843,
 'usf': 7273,
 'guess': 3300,
 'car': 1675,
 'rajini': 5595,
 'comes': 1925,
 'have': 3393,
 'grinder': 3277,
 'hmmm': 3484,
 'thought': 6910,
 'hours': 3540,
 'punish': 5534,
 'lor': 4234,
 'anyway': 1012,
 'thk': 6901,
 'cant': 1668,
 'tickets': 6937,
 'like': 4139,
 'quite': 5571,
 'frens': 3027,
 'darren': 2186,
 'wif': 7559,
 'obviously': 4918,
 'because': 1303,
 'cool': 2019,
 'college': 1914,
 'life': 4128,
 'home': 3499,
 'wish': 7589,
 'great': 3268,
 'semester': 6052,
 'wrong': 7674,
 'de': 2206,
 'happy': 3368,
 'sad': 5916,
 'thing': 6890,
 'about': 764,
 'past': 5145,
 'morning': 4630,
 'those': 6906,
 'cocksuckers': 1894,
 'makes': 4358,
 'feel': 2829,
 'ipads': 3762,
 'worthless': 7655,
 'garbage': 3108,
 'novelty': 4873,
 'items': 3789,
 'bad': 1214,
 'wanting': 7429,
 'tried': 7090,
 'contact': 1995,
 're': 5628,
 'phone': 5223,
 '750': 622,
 'anytime': 1011,
 'mins': 4534,
 'half': 3336,
 'price': 5441,
 'rental': 5740,
 'camcorder': 1652,
 '08000930705': 51,
 'delivery': 2258,
 'wed': 7481,
 'what': 7526,
 'meh': 4464,
 'first': 2895,
 'gained': 3094,
 'kg': 3954,
 'since': 6217,
 'took': 7021,
 'second': 6017,
 'blood': 1421,
 'sugar': 6624,
 'tests': 6833,
 'her': 3445,
 'pressure': 5430,
 'within': 7598,
 'normal': 4852,
 'limits': 4150,
 'honestly': 3503,
 'made': 4334,
 'lovely': 4259,
 'cup': 2134,
 'tea': 6779,
 'promptly': 5494,
 'dropped': 2486,
 'keys': 3951,
 'burnt': 1594,
 'fingers': 2882,
 'getting': 3157,
 'hey': 3454,
 'something': 6344,
 'last': 4048,
 'think': 6892,
 'wun': 7686,
 'signing': 6204,
 'tmr': 6973,
 'hee': 3423,
 'xy': 7707,
 'trying': 7111,
 'smth': 6308,
 'eat': 2538,
 'havent': 3396,
 'yeah': 7723,
 'random': 5605,
 'dude': 2505,
 'change': 1745,
 'sheets': 6120,
 'party': 5134,
 'never': 4789,
 'study': 6583,
 'safe': 5919,
 'lookatme': 4224,
 'purchase': 5539,
 'clip': 1862,
 'been': 1315,
 '35p': 459,
 'mmsto': 4575,
 '32323': 453,
 '20': 353,
 'cost': 2038,
 'which': 7540,
 'isnt': 3782,
 'ya': 7709,
 'love': 4256,
 'wet': 7523,
 'right': 5819,
 'claire': 1842,
 'havin': 3397,
 'borin': 1461,
 'alone': 929,
 'cum': 2131,
 'chat': 1765,
 '09099725823': 252,
 'xx': 7699,
 'calls': 1648,
 'minmoremobsemspobox45po139wa': 4531,
 'john': 3866,
 'lennon': 4105,
 'would': 7659,
 'sure': 6668,
 'wot': 7656,
 'drinkin': 2475,
 'dancin': 2172,
 'eatin': 2540,
 'cinema': 1835,
 'knew': 3987,
 'murder': 4694,
 'exactly': 2712,
 '09061743811': 204,
 'abta': 772,
 'complimentary': 1954,
 'await': 1180,
 'collection': 1912,
 'cs': 2114,
 'box': 1479,
 '326': 454,
 'pity': 5258,
 'mood': 4623,
 'other': 5036,
 'suggestions': 6628,
 '3510i': 458,
 'colour': 1916,
 'delivered': 2256,
 'tomorrow': 7006,
 '200': 354,
 'minutes': 4538,
 '100': 262,
 '8000930705': 640,
 'fuck': 3058,
 'babe': 1202,
 'let': 4112,
 'towards': 7052,
 'net': 4780,
 'crave': 2079,
 'note': 4861,
 'anyone': 1004,
 'calling': 1646,
 'asks': 1109,
 'type': 7159,
 'disconnect': 2366,
 'iz': 3802,
 'attempt': 1140,
 'terrorist': 6828,
 'card': 1676,
 'itz': 3797,
 'confirmd': 1976,
 'motorola': 4642,
 'verified': 7321,
 'cnn': 1884,
 'ibn': 3606,
 'receive': 5664,
 'before': 1320,
 'noon': 4842,
 'xmas': 7695,
 'years': 7725,
 'sale': 5927,
 'club': 1876,
 '10am': 271,
 'till': 6946,
 '8pm': 721,
 'thurs': 6930,
 'fri': 3030,
 'sat': 5954,
 'night': 4808,
 'selling': 6049,
 'class': 1847,
 'bsn': 1563,
 'advising': 846,
 'promise': 5489,
 'pics': 5238,
 'ttyl': 7120,
 'lar': 4042,
 'carry': 1695,
 'heavy': 3421,
 'num': 4890,
 '98321561': 735,
 'familiar': 2789,
 'building': 1580,
 'coat': 1889,
 'sick': 6193,
 'hurry': 3585,
 'wear': 7471,
 'gym': 3316,
 'credits': 2091,
 'topped': 7032,
 'http': 3560,
 'bubbletext': 1570,
 'com': 1919,
 'renewal': 5737,
 'pin': 5251,
 'tgxxrz': 6846,
 'lemme': 4103,
 'goin': 3202,
 'nope': 4845,
 'drivin': 2481,
 'neva': 4787,
 'develop': 2299,
 'photos': 5229,
 'pic': 5233,
 'ill': 3640,
 'evening': 2682,
 'ideas': 3618,
 'thinkin': 6894,
 'dip': 2349,
 'cell': 1728,
 'dead': 2207,
 'him': 3467,
 'respond': 5778,
 'else': 2584,
 'shall': 6105,
 'approaching': 1039,
 'very': 7325,
 'year': 7724,
 'sankranti': 5943,
 'republic': 5757,
 'valentines': 7293,
 'shivratri': 6143,
 'ugadi': 7166,
 'fools': 2959,
 'may': 4431,
 'independence': 3686,
 'friendship': 3037,
 'father': 2809,
 'teachers': 6782,
 'childrens': 1806,
 'birthday': 1387,
 'ganesh': 3103,
 'festival': 2842,
 'dasara': 2189,
 'diwali': 2385,
 'mornings': 4631,
 'afternoons': 863,
 'evenings': 2683,
 'nights': 4811,
 'rememberi': 5725,
 'wishing': 7592,
 'raj': 5592,
 'rounder': 5868,
 'required': 5761,
 'valued': 7298,
 'pleased': 5285,
 'advise': 845,
 'following': 2950,
 'recent': 5668,
 'review': 5805,
 'awarded': 1184,
 '1500': 311,
 'bonus': 1445,
 'prize': 5458,
 '09066364589': 233,
 'mm': 4569,
 'feeling': 2831,
 'sleepy': 6267,
 'itself': 3795,
 'kind': 3971,
 'missed': 4548,
 'train': 7059,
 'asthma': 1123,
 'attack': 1139,
 'nxt': 4902,
 'hr': 3555,
 'hmv': 3487,
 'special': 6401,
 '500': 543,
 'pounds': 5375,
 'genuine': 3143,
 'vouchers': 7380,
 'won': 7622,
 'easy': 2537,
 '86688': 690,
 '100percent': 267,
 'yetunde': 7740,
 'water': 7452,
 'nt': 4882,
 'joking': 3874,
 'seriously': 6074,
 'told': 6996,
 'din': 2341,
 'welp': 7508,
 'sort': 6369,
 'semiobscure': 6054,
 'internet': 3739,
 'loyalty': 4271,
 'nokia6650': 4834,
 '10': 261,
 'txtauction': 7149,
 'word': 7636,
 'start': 6491,
 '81151': 655,
 '4t': 532,
 'ctxt': 2122,
 'tc': 6775,
 '150p': 312,
 'mtmsg': 4672,
 'give': 3175,
 'ride': 5818,
 'grumble': 3290,
 'aft': 860,
 'lunch': 4290,
 'meetin': 4458,
 'hear': 3414,
 'fr': 3001,
 'lot': 4242,
 'ar': 1050,
 'alright': 933,
 'justthought': 3906,
 'sayhey': 5970,
 'doin': 2417,
 'nearly': 4757,
 'endof': 2606,
 'wk': 7605,
 'offdam': 4932,
 'nevamind': 4788,
 '2hook': 402,
 'sn': 6309,
 'uwant': 7285,
 'm8': 4315,
 'lovejen': 4258,
 'carlos': 1690,
 'taking': 6739,
 'sweet': 6695,
 'usual': 7277,
 'patty': 5152,
 'smoke': 6298,
 'haul': 3388,
 'ass': 1114,
 'sign': 6199,
 'choose': 1820,
 'show': 6171,
 'city': 1837,
 'break': 1514,
 'could': 2047,
 'summer': 6637,
 'shopping': 6152,
 'spree': 6457,
 'store': 6545,
 '88039': 701,
 'skilgme': 6245,
 'tscs087147403231winawk': 7116,
 'age16': 870,
 '50perwksub': 550,
 'also': 935,
 'fine': 2880,
 'complete': 1949,
 'course': 2059,
 'yar': 7716,
 'tot': 7043,
 'happen': 3359,
 'long': 4219,
 'ago': 875,
 'several': 6088,
 'sir': 6227,
 'wake': 7407,
 'knowing': 3991,
 'sleep': 6262,
 'full': 3068,
 'opportunity': 5002,
 'kiss': 3977,
 'vl': 7365,
 'adsense': 838,
 'approved': 1041,
 'nice': 4804,
 'working': 7642,
 'god': 3197,
 'almost': 928,
 'brought': 1553,
 'gmw': 3186,
 'ltd': 4278,
 'connected': 1984,
 'lil': 4145,
 'fever': 2845,
 'forwarded': 2992,
 '21870000': 366,
 'mailbox': 4351,
 'messaging': 4494,
 'alert': 908,
 '40': 484,
 'matches': 4413,
 '09056242159': 177,
 'retrieve': 5796,
 'messages': 4493,
 'cc100p': 1719,
 'feb': 2824,
 'frnds': 3044,
 'evn': 2700,
 'married': 4397,
 'ignore': 3631,
 'lose': 4236,
 'evr': 2704,
 'alrite': 934,
 'hunny': 3581,
 'end': 2602,
 'down': 2453,
 'town': 7053,
 'jus': 3902,
 'pub': 5525,
 'instead': 3726,
 'chillin': 1809,
 'mo': 4579,
 'bedroom': 1312,
 'jen': 3838,
 'xxx': 7702,
 'connection': 1985,
 'bw': 1614,
 'umma': 7178,
 'called': 1640,
 'freemsg': 3021,
 'mini': 4527,
 'digital': 2336,
 'camera': 1654,
 'snap': 6310,
 'quizclub': 5575,
 'opt': 5004,
 '80122300p': 645,
 'sp': 6387,
 'rwm': 5906,
 'ph': 5214,
 '08704050406': 83,
 'doesnt': 2408,
 'log': 4206,
 'heehee': 3424,
 'funny': 3078,
 'tho': 6905,
 'loverboy': 4262,
 'had': 3324,
 'picture': 5240,
 'ache': 797,
 'between': 1357,
 'legs': 4099,
 'saw': 5968,
 'disappeared': 2360,
 ...}

In [25]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
np.where(X_train_np[0]!=0)

(array([1083, 2036, 2164, 2843, 4345, 6948, 7445]),)

#### **Naive Bayes Classifier**

In [27]:
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [28]:
y_pred = model.predict(X_test_cv)

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       968
           1       0.95      0.96      0.96       147

    accuracy                           0.99      1115
   macro avg       0.97      0.98      0.97      1115
weighted avg       0.99      0.99      0.99      1115

#### **Test on a random datapoint**

In [30]:
message = {"Upto 20% off on parking, exclusing offer just for you"}

In [31]:
message_cnt = v.transform(message)

model.predict(message_cnt)

array([1])